# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "vilnius-tech"
version = "0.1.0"
entrypoint = "src/index.typ"
authors = ["Dovias"]
license = "Unlicense"
description = ""
homepage = ""
repository = ""
keywords = []
categories = []
disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "document.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
